### PR TITLE
Add support for SNK Neo Geo Arcade Stick Pro on Mac OS X

### PR DESCRIPTION
**Pull request by kemar**
Add support for SNK Neo Geo Arcade Stick Pro on Mac OS X.

Product page: https://www.snk-corp.co.jp/us/neogeoarcadestickpro/

### CODE REVIEW

**Comment by offalynne** [comment]
Thanks, would love to have Windows and Linux as well in the future if you're able 👍

**Comment by kemar** [comment]
Thanks for merging the PR!

My only computer is a Mac right now, so I cannot map the stick for Windows and Linux 😔

**Comment by offalynne** [comment]
@kemar how did you map the buttons ? did you follow the "Arcade" format per the REAMDE graphice https://github.com/mdqinc/SDL_GameControllerDB/blob/master/mapping_guide.png ?

**Comment by kemar** [comment]
@offalynne I used SDL2 Gamepad Tool but didn't pay attention to the [note](https://github.com/mdqinc/SDL_GameControllerDB/blob/793346bc4eaefe25af23c042cc4d74a52b9bc99e/README.md?plain=1#L39).

Does this break something? And if so, how to fix it?

**Comment by offalynne** [comment]
@kemar the object of the ddb is to present a correct unified layout so apps behave predictably across input devices enabling consistent developer defined input schemes and surfacing controls to players (eg. through text or icon prompts)

I asked a Windows user for a mapping and they supplied the following

`03000000bc2000000155000000000000,NeoGeo G1 Pro D-Input,platform:Windows,a:b0,b:b1,x:b3,y:b4,back:b10,start:b11,leftshoulder:b6,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,lefttrigger:b7,righttrigger:b2,`

if you could, please reauthor the mapping according to the "Arcade" scheme

**Comment by offalynne** [comment]
One last consdieration: how have you configured the joystick ?

image

The Windows user selected "PC2" mode

**Comment by offalynne** [comment]
I've got in touch with another user who has clarified all of the above -- no further follow up is needed 👍

**Comment by kemar** [comment]
> I've got in touch with another user who has clarified all of the above -- no further follow up is needed 👍

Cool because I didn't understand what could possibly be wrong with this mapping 😄

**Comment by offalynne** [comment]
Since there are 2 modes with conflicting GUIDs and different button layouts, I'm going to remove this mapping. If you want to revisit this in the future, you can contribute an upstream mapping to SDL, since SDL's db includes duplicate GUIDs differentiated on device CRC.  (See https://github.com/mdqinc/SDL_GameControllerDB?tab=readme-ov-file#sdl)

**Comment by kemar** [comment]
Ok @offalynne I understand.

Do you mean contributing to https://github.com/libsdl-org/SDL?

**Comment by offalynne** [comment]
Yes.

To contribute, build the mapping tool here <https://github.com/libsdl-org/SDL/blob/main/test/testcontroller.c>
and submit the mapping here <https://github.com/libsdl-org/SDL/blob/main/src/joystick/SDL_gamepad_db.h>

**Comment by kemar** [comment]
Ok thanks, that's very clear. I may try this in the coming weeks but I'll need to learn a bit about C.

**Pull request merged**
