### PR TITLE
Fix Clockwork Pi Devterm GUID

### PR DESCRIPTION
**Pull request by xordspar0**
Somehow I messed up the GUID when I submitted this controller last year.
I fixed this in my local copy, but forgot to submit the fix upstream
until now.

### CODE REVIEW

**Comment by xordspar0** [comment]
sdl2-jstest output:

```
Found 1 joystick(s)

Joystick Name:     'ClockworkPI DevTerm'
Joystick GUID:     0300280aaf1e00002400000010010000
Joystick Number:    0
Number of Axes:     5
Number of Buttons: 32
Number of Hats:     1
Number of Balls:    0
GameControllerConfig:
  Name:    'Clockwork Pi DevTerm'
  Mapping: '0300280aaf1e00002400000010010000,Clockwork Pi DevTerm,a:b2,b:b1,back:b8,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,start:b9,x:b3,y:b0,platform:Linux,crc:0a28,'
```

Also tested and working with some [LOVE](https://love2d.org/wiki/love.joystick.loadGamepadMappings) games.

**Comment by offalynne** [comment]
No change is needed as the current db entry should work fine -- the `280a` in `0300280aaf1e00002400000010010000` is a CRC and does not go in the db GUID, see https://github.com/mdqinc/SDL_GameControllerDB/issues/609#issuecomment-1336432046

**Comment by xordspar0** [comment]
Ok, thanks for the context. Doing some more testing, I see that sdl2-jstest works with the CRC zero-ed out, but the LOVE games I'm testing do not work. I'm using SDL 2.26.5. I'll keep investigating this on my own to see what's going on and report back here if I learn any thing interesting.

**Comment by xordspar0** [comment]
Oh! LOVE has an independent implementation of `SDL_GameControllerAddMappingsFromRW()`: https://github.com/love2d/love/blob/b69a22dca399c51e0ac4e814619abd9cfa378304/src/modules/joystick/sdl/JoystickModule.cpp#L490-L494

I'll take this up with LOVE; it should be possible to make their implementation compatible with SDL's new bahavior.

**Comment by xordspar0** [comment]
There's actually nothing wrong with LOVE's implementation, it's just that a lot of games rely on GameControllerAdded events for controllers already plugged in when the game starts, and those events don't fire when you load new game controller mappings. So, PSA:

1. If you're playing a game and your controller isn't recognized, try unplugging it and plugging it in again.
2. If you're making a game, remember to rescan for controllers after you load new game controller mappings!

More discussion here: https://discourse.libsdl.org/t/deviced-added-events-for-devices-plugged-in-at-game-start/55039

**Pull request closed without merging**
