### PR TITLE
Added Kreo Mirage wired configurations

### PR DESCRIPTION
**Pull request by RinzlerCR7**
Added Kreo Mirage wired configuration for the following modes:
- Blue (Linux)
- Red (Linux & Windows)
- Green (Windows)

### CODE REVIEW

**Comment by offalynne** [comment]
These GUIDs are all in duplicate of other mainstream/generic devices unfortunately, thank you, though !

**Comment by RinzlerCR7** [comment]
Hi @offalynne , I checked the list. GUID of `Kreo Mirage (Green)` is duplicate in the list but the rest are not. Should I remove `Kreo Mirage (Green)` & resubmit or if I'm missing something please let me know.

**Comment by offalynne** [comment]
Hi @RinzlerCR7, here are the duplicates

1. `03000000632500007505000000000000,Kreo Mirage (Green)` -> https://github.com/mdqinc/SDL_GameControllerDB/blob/e9d11d9bdbdd19269b18d85908bd96525a3cb277/gamecontrollerdb.txt#L525
2. `030000005e0400008e02000000007801,Kreo Mirage (Red)` -> Handled by XInput driver per suffix `780x` (see #478)
3. `03008fe54c050000c405000000016800,Kreo Mirage (Blue)` -> Handled by HIDAPI driver per suffix `6800` (see #478)
4. 030081b85e0400008e02000072050000,Kreo Mirage (Red)` -> Contains a CRC which we remove from the GUID before adding to the DB, becomes `030000005e0400008e02000072050000` which is in duplicate: https://github.com/mdqinc/SDL_GameControllerDB/blob/e9d11d9bdbdd19269b18d85908bd96525a3cb277/gamecontrollerdb.txt#L1724

**Comment by RinzlerCR7** [comment]
Ah... thanks for letting me know. Just a question:
Will remapping `030000005e0400008e02000072050000` impact `030081b85e0400008e02000072050000` too?

**Comment by offalynne** [comment]
Depends on your version of SDL. If you want to override the other mapping, remove the CRC from the GUID and add it as a field: `030000005e0400008e02000072050000,Name,[...],crc:81b8,`

**Comment by RinzlerCR7** [comment]
Sorry to bother again, if I want to remap

> `03008fe54c050000c405000000016800` (Blue) > Handled by HIDAPI driver per suffix 6800 (see https://github.com/mdqinc/SDL_GameControllerDB/issues/478)

which GUID should I edit?

**Comment by offalynne** [comment]
add a mapping for `030000004c050000c405000000016800`

**Pull request closed without merging**
